# Generated by Django 3.2.9 on 2021-11-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=200)),
                ('metadata', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='files/')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
