# Generated by Django 3.2.9 on 2021-11-03 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='metadata',
        ),
    ]
